In [2]:
import numpy as np
a=np.array([1,2,3,4,5])
print("adding 2 to given numpy:")
print(a+2)
print("multiplying 3 to given numpy:")
print(a*3)
print("dividing 2 from given numpy:")
print(a/2)


adding 2 to given numpy:
[3 4 5 6 7]
multiplying 3 to given numpy:
[ 3  6  9 12 15]
dividing 2 from given numpy:
[0.5 1.  1.5 2.  2.5]


In [2]:
import numpy as np
a=np.array([1,2,3,6,4,5])
print("reversing the above numpy array");
print(a[::-1])
print(np.flip(a))


reversing the above numpy array
[5 4 6 3 2 1]
[5 4 6 3 2 1]


In [16]:
import numpy as np
from collections import Counter
x = np.array([1,2,3,4,5,1,2,1,1,1])
counter=Counter(x);
#counter ka kaam hain counts the occurence of each unique value
print(counter)
most_common,frequency=counter.most_common(1)[0]
print("most common value is",most_common)
print("frequncy is",frequency)
indices=np.where(x==most_common)[0]
print("indices are",indices);
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
counter=Counter(y);
most_commonval,frequency2=counter.most_common(1)[0];
print("most common value is",most_commonval)
print("frequncy is",frequency2)
indices2=np.where(y==most_common)[0]
print("indices are",indices2);




Counter({1: 5, 2: 2, 3: 1, 4: 1, 5: 1})
most common value is 1
frequncy is 5
indices are [0 5 7 8 9]
most common value is 1
frequncy is 3
indices are [0 1 2]


In [21]:
arr=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print("1st row,2nd coloumn:")#index row=0,coloumn=1
print(arr[0,1])
print("3rd row,1st coloumn:")
print(arr[2,0])

1st row,2nd coloumn:
20
3rd row,1st coloumn:
70


In [22]:
your_name=np.linspace(10,100,25)#linspace(start,stop,totalnum in the array)
print("array is",your_name);
print("the dimensions of array are",your_name.ndim)
print("shape is:",your_name.shape)
print("size is:",your_name.size)
print("data type :",your_name.dtype)
print("total. bytes consumed by the array:",your_name.nbytes)
print("transpose is",your_name.T)


array is [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
the dimensions of array are 1
shape is: (25,)
size is: 25
data type : float64
total. bytes consumed by the array: 200
transpose is [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [25]:
import numpy as np
ucs420_Gurvani=np.array([[10,20,30,40],
                          [50,60,70,80],
                          [90,100,110,120]])
print("mean",np.mean(ucs420_Gurvani))
print("median",np.median(ucs420_Gurvani))
print("max",np.max(ucs420_Gurvani))
print("min",np.min(ucs420_Gurvani))
print("unique",np.unique(ucs420_Gurvani))
reshape=ucs420_Gurvani.reshape(4,3)
print("reshape",reshape)
resize=np.resize(ucs420_Gurvani, (2, 3))
print("resize",resize)


mean 65.0
median 65.0
max 120
min 10
unique [ 10  20  30  40  50  60  70  80  90 100 110 120]
reshape [[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]
resize [[10 20 30]
 [40 50 60]]
